pipeline {
    agent any
    tools {
        nodejs "nodeJs"
    }
    environment {
        DOCKER_BUILDKIT = "1" // BuildKit 활성화
        DOCKER_IMAGE = "ejujin/docker-nodejs-demo"
    }
    stages {
        stage('Preparation') {
            steps {
                script {
                    checkout scm
                    sh "git rev-parse --short HEAD > .git/commit-id"
                    env.COMMIT_ID = readFile('.git/commit-id').trim()

                    def nodejsTool = tool name: 'nodeJs', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
                    env.PATH = "${nodejsTool}/bin:${env.PATH}"
                }
            }
        }

        stage('Build') {
            steps {
                sh 'node -v'
                sh 'npm -v'
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh """
                            echo "Logging into Docker Hub..."
                            echo "\$DOCKER_PASS" | docker login -u "\$DOCKER_USER" --password-stdin

                            echo "Setting up Docker Buildx..."
                            docker buildx create --name mybuilder --use
                            docker buildx inspect --bootstrap

                            echo "Building Docker image with Buildx..."
                            docker buildx build --platform linux/amd64 -t \$DOCKER_IMAGE:\$COMMIT_ID --push .
                        """
                    }
                }
            }
        }
    }
}
