pipeline {
    agent any
    tools {
        nodejs "nodeJs"
    }
    environment {
        DOCKER_BUILDKIT = "1" // BuildKit 활성화
        DOCKER_REGISTRY = 'registry-1.docker.io'
        DOCKER_IMAGE = "ejujin/docker-nodejs-demo"
    }
    stages {
        stage('Preparation') {
            steps {
                script {
                    checkout scm
                    sh "git rev-parse --short HEAD > .git/commit-id"
                    env.COMMIT_ID = readFile('.git/commit-id').trim()

                    def nodejsTool = tool name: 'nodeJs', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
                    env.PATH = "${nodejsTool}/bin:${env.PATH}"
                }
            }
        }

        stage('Build') {
            steps {
                sh 'node -v'
                sh 'npm -v'
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: '6e025c89-6fb8-4e11-9894-10f0b0a40896', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh """
                            echo "Logging into Docker Hub..."
                            echo "\$DOCKER_PASS" | docker login -u "\$DOCKER_USER" --password-stdin

                            echo "Building Docker image with BuildKit..."
                            export DOCKER_BUILDKIT=1
                            docker build -t \$DOCKER_IMAGE:\$COMMIT_ID .

                            echo "Pushing Docker image..."
                            docker push \$DOCKER_IMAGE:\$COMMIT_ID
                        """
                    }
                }
            }
        }
    }
}
